export const EVENT = Object.freeze({
	ADD: 'EVENT_ADD',
	DELETE: 'EVENT_DELETE',
	CHANGE_DONE: 'EVENT_CHANGE_DONE'
});

export const API = Object.freeze({
	GET_ONE_REQUEST: 'API_GET_ONE_REQUEST',
	GET_ALL_REQUEST: 'API_GET_ALL_REQUEST',
	ADD_REQUEST: 'API_ADD_REQUEST',
	DELETE_REQUEST: 'API_DELETE_REQUEST',
	UPDATE_REQUEST: 'API_UPDATE_REQUEST',

	GET_ONE_SUCCESS: 'API_GET_ONE_SUCCESS',
	GET_ALL_SUCCESS: 'API_GET_ALL_SUCCESS',
	ADD_SUCCESS: 'API_ADD_SUCCESS',
	DELETE_SUCCESS: 'API_DELETE_SUCCESS',
	UPDATE_SUCCESS: 'API_UPDATE_SUCCESS',

	GET_ONE_FAILURE: 'API_GET_ONE_FAILURE',
	GET_ALL_FAILURE: 'API_GET_ALL_FAILURE',
	ADD_FAILURE: 'API_ADD_FAILURE',
	DELETE_FAILURE: 'API_DELETE_FAILURE',
	UPDATE_FAILURE: 'API_UPDATE_FAILURE',

	CHANGE_STATUS_REQUEST: `API_CHANGE_STATUS_REQUEST`,
	CHANGE_STATUS_SUCCESS: `API_CHANGE_STATUS_SUCCESS`,
	CHANGE_STATUS_FAILURE: `API_CHANGE_STATUS_FAILURE`,

	CLICKED_ELEMENT: 'API_CLICKED_ELEMENT',
	CLICKED_ELEMENT_CLEAR: 'API_CLICKED_ELEMENT_CLEAR'
});

export const AUTH = Object.freeze({
	SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
	SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'AUTH_SIGN_IN_FAILURE',

	SIGN_OUT_REQUEST: 'AUTH_SIGN_OUT_REQUEST',
	SIGN_OUT_SUCCESS: 'AUTH_SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'AUTH_SIGN_OUT_FAILURE',

	SIGN_UP_REQUEST: 'AUTH_SIGN_UP_REQUEST',
	SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'AUTH_SIGN_UP_FAILURE',

	SIGN_UP_CLEAR: 'AUTH_SIGN_UP_CLEAR'
});

export const USER = Object.freeze({
	GET_INFO_REQUEST: 'USER_GET_INFO_REQUEST',
	GET_INFO_SUCCESS: 'USER_GET_INFO_SUCCESS',
	GET_INFO_FAILURE: 'USER_GET_INFO_FAILURE'
});

export const TAB = Object.freeze({
	CHANGE: 'TAB_CHANGE'
});

export const TAB_FORM = Object.freeze({
	CLOSE: 'TAB_FORM_CLOSE',
	CHANGE: 'TAB_FORM_CHANGE'
});
